# coding: utf-8

# EN:          electronegativity
# group:       english name of a group the element belongs to
# ATOM_WEIGHT: atomic weight
# NAMES:       language dependent element names (as dictionary)
# NAME_LAT:    latin name
# ATOM_SYMBOL: atom symbol
# ORBITALS:    electron structure of occupied orbitals
# DESC:        short czech description of the element
# OX_NUMBERS:  oxidation numbers that the element usually has in compounds
# ROW:         number of row where the element resides in the periodic table
# COLUMN:      number of column where the element resides in the periodic table
#                  101-114 is used for lanthanoids and actionoids that are normally
#                  not shown as part of the table
# PROTON_NUMBER: number of protons, also the index in the table


symbol2properties = {
'H': { 'EN': 2.1, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 1.00794, 'NAME_LAT': u'hydrogenium', 'COLUMN': 1, 'ATOM_SYMBOL': u'H', 'ORBITALS': '1s1',
'OX_NUMBERS': [1, -1], 'NAMES':{"ru":u"водород","fr":u"hydrogène","en":u"hydrogen","nl":u"waterstof","pt":u"Hidrogénio","de":u"wasserstoff","tr":u"hidrojen","sv":u"väte","ar":u"هيدروجين","cs":u"vodík","fi":u"vety","ja":u"水素","es":u"hidrógeno"},
'PROTON_NUMBER': 1, 'DESC':{"cs":u"bezbarvý plyn","en":u"colourless gas"},
'ROW': 1, },
'He': { 'EN': 0.0, 'group':{"cs":u"inertní plyny","en":u"inert-gases","pt":u"gases inertes"},
'ATOM_WEIGHT': 4.002602, 'NAME_LAT': u'helium', 'COLUMN': 18, 'ATOM_SYMBOL': u'He', 'ORBITALS': '1s2',
'OX_NUMBERS': [], 'NAMES':{"ru":u"гелий","fr":u"hélium","en":u"helium","nl":u"helium","pt":u"Hélio","de":u"helium","tr":u"helyum","sv":u"helium","ar":u"هيليوم","cs":u"helium","fi":u"helium","ja":u"ジリウム","es":u"hélio"},
'PROTON_NUMBER': 2, 'DESC':{"cs":u"bezbarvý inertní plyn","en":u"colourless inert gas"},
'ROW': 1, },
'Li': { 'EN': 0.98, 'group':{"cs":u"alkalické kovy","en":u"alkali-metals","pt":u"metais alcalinos"},
'ATOM_WEIGHT': 6.941, 'NAME_LAT': u'lithium', 'COLUMN': 1, 'ATOM_SYMBOL': u'Li', 'ORBITALS': '1s2 2s1',
'OX_NUMBERS': [1], 'NAMES':{"ru":u"литий","fr":u"lithium","en":u"lithium","nl":u"lithium","pt":u"Litio","de":u"lithium","tr":u"lityum","sv":u"litium","ar":u"ليثيوم","cs":u"lithium","fi":u"litium","ja":u"リチウム","es":u"lítio"},
'PROTON_NUMBER': 3, 'DESC':{"cs":u"měkký lehký stříbrolesklý kov","en":u"soft light silvery metal"},
'ROW': 2, },
'Be': { 'EN': 1.57, 'group':{"cs":u"kovy alkalických zemin","en":u"alkali-earth-metals","pt":u"metais alcalino-terrosos"},
'ATOM_WEIGHT': 9.012182, 'NAME_LAT': u'beryllium', 'COLUMN': 2, 'ATOM_SYMBOL': u'Be', 'ORBITALS': '1s2 2s2',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"бериллий","fr":u"béryllium","en":u"beryllium","nl":u"beryllium","pt":u"Berílio","de":u"beryllium","tr":u"berilyum","sv":u"beryllium","ar":u"بيريليوم","cs":u"beryllium","fi":u"beryllium","ja":u"スリリウム","es":u"berílio"},
'PROTON_NUMBER': 4, 'DESC':{"cs":u"lehký stříbrolesklý kov","en":u"light silvery metal"},
'ROW': 2, },
'B': { 'EN': 2.04, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 10.811, 'NAME_LAT': u'borium', 'COLUMN': 13, 'ATOM_SYMBOL': u'B', 'ORBITALS': '1s2 2s2 2p1',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"бор","fr":u"boron","en":u"boron","nl":u"boor","pt":u"Bóro","de":u"bor","tr":u"bor","sv":u"bor","ar":u"بورون","cs":u"bor","fi":u"boori","ja":u"硼素","es":u"boro"},
'PROTON_NUMBER': 5, 'DESC':{"cs":u"pevná látka","en":u"solid substance"},
'ROW': 2, },
'C': { 'EN': 2.55, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 12.0107, 'NAME_LAT': u'carbonium', 'COLUMN': 14, 'ATOM_SYMBOL': u'C', 'ORBITALS': '1s2 2s2 2p2',
'OX_NUMBERS': [4, 2, -4], 'NAMES':{"ru":u"углерод","fr":u"carbone","en":u"carbon","nl":u"koolstof","pt":u"Carbono","de":u"kohlenlstoff","tr":u"karbon","sv":u"kol","ar":u"كربون","cs":u"uhlík","fi":u"hiili","ja":u"炭素","es":u"carbono"},
'PROTON_NUMBER': 6, 'DESC':{"cs":u"měkký černý grafit, tvrdý bezbarvý diamant","en":u"soft black graphite, hard colourless diamond"},
'ROW': 2, },
'N': { 'EN': 3.04, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 14.0067, 'NAME_LAT': u'nitrogenium', 'COLUMN': 15, 'ATOM_SYMBOL': u'N', 'ORBITALS': '1s2 2s2 2p3',
'OX_NUMBERS': [5, 4, 3, 2, -3], 'NAMES':{"ru":u"азот","fr":u"azote","en":u"nitrogen","nl":u"stikstof","pt":u"Nitrogênio","de":u"stickstoff","tr":u"azot","sv":u"kväve","ar":u"نيتروجين","cs":u"dusík","fi":u"typpi","ja":u"窒素","es":u"nitrógeno"},
'PROTON_NUMBER': 7, 'DESC':{"cs":u"bezbarvý inertní plyn","en":u"colourless inert gas"},
'ROW': 2, },
'O': { 'EN': 3.44, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 15.9994, 'NAME_LAT': u'oxygenium', 'COLUMN': 16, 'ATOM_SYMBOL': u'O', 'ORBITALS': '1s2 2s2 2p4',
'OX_NUMBERS': [-2, -1], 'NAMES':{"ru":u"кислород","fr":u"oxygène","en":u"oxygen","nl":u"zuurstof","pt":u"Oxigénio","de":u"sauerstoff","tr":u"oksijen","sv":u"syre","ar":u"أكسجين","cs":u"kyslík","fi":u"happi","ja":u"酸素","es":u"oxígeno"},
'PROTON_NUMBER': 8, 'DESC':{"cs":u"reaktivní bezbarvý plyn","en":u"reactive colourless gas"},
'ROW': 2, },
'F': { 'EN': 3.98, 'group':{"cs":u"halogeny","en":u"halogens","pt":u"halogéneos"},
'ATOM_WEIGHT': 18.9984032, 'NAME_LAT': u'fluorum', 'COLUMN': 17, 'ATOM_SYMBOL': u'F', 'ORBITALS': '1s2 2s2 2p5',
'OX_NUMBERS': [-1], 'NAMES':{"ru":u"фтор","fr":u"fluor","en":u"fluorine","nl":u"fluor","pt":u"Flúor","de":u"fluor","tr":u"fluor","sv":u"fluor","ar":u"فلور","cs":u"fluor","fi":u"fluori","ja":u"サィ素","es":u"flúor"},
'PROTON_NUMBER': 9, 'DESC':{"cs":u"reaktivní plyn","en":u"reactive gas"},
'ROW': 2, },
'Ne': { 'EN': 0.0, 'group':{"cs":u"inertní plyny","en":u"inert-gases","pt":u"gases inertes"},
'ATOM_WEIGHT': 20.1797, 'NAME_LAT': u'neon', 'COLUMN': 18, 'ATOM_SYMBOL': u'Ne', 'ORBITALS': '1s2 2s2 2p6',
'OX_NUMBERS': [], 'NAMES':{"ru":u"неон","fr":u"néon","en":u"neon","nl":u"neon","pt":u"Neônio","de":u"neon","tr":u"neon","sv":u"neon","ar":u"نيون","cs":u"neon","fi":u"neon","ja":u"キオン","es":u"neón"},
'PROTON_NUMBER': 10, 'DESC':{"cs":u"bezbarvý inertní plyn","en":u"colourless inert gas"},
'ROW': 2, },
'Na': { 'EN': 0.93, 'group':{"cs":u"alkalické kovy","en":u"alkali-metals","pt":u"metais alcalinos"},
'ATOM_WEIGHT': 22.98977, 'NAME_LAT': u'natrium', 'COLUMN': 1, 'ATOM_SYMBOL': u'Na', 'ORBITALS': '1s2 2s2 2p6 3s1',
'OX_NUMBERS': [1], 'NAMES':{"ru":u"натрий","fr":u"sodium","en":u"sodium","nl":u"natrium","pt":u"Sódio","de":u"natrium","tr":u"sodyum","sv":u"natrium","ar":u"صوديوم","cs":u"sodík","fi":u"natrium","ja":u"オエリウム","es":u"sodio"},
'PROTON_NUMBER': 11, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 3, },
'Mg': { 'EN': 1.31, 'group':{"cs":u"kovy alkalických zemin","en":u"alkali-earth-metals","pt":u"metais alcalino-terrosos"},
'ATOM_WEIGHT': 24.305, 'NAME_LAT': u'magnesium', 'COLUMN': 2, 'ATOM_SYMBOL': u'Mg', 'ORBITALS': '1s2 2s2 2p6 3s2',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"магний","fr":u"magnésium","en":u"magnesium","nl":u"magnesium","pt":u"Magnésio","de":u"magnesium","tr":u"magnezyum","sv":u"magnesium","ar":u"مغنيسيوم","cs":u"hořčík","fi":u"magnesium","ja":u"マグキシウム","es":u"magnesio"},
'PROTON_NUMBER': 12, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 3, },
'Al': { 'EN': 1.61, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 26.981538, 'NAME_LAT': u'aluminium', 'COLUMN': 13, 'ATOM_SYMBOL': u'Al', 'ORBITALS': '1s2 2s2 2p6 3s2 3p1',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"алюминий","fr":u"aluminium","en":u"aluminium","nl":u"aluminium","pt":u"Alumínio","de":u"aluminium","tr":u"alüminyum","sv":u"aluminium","ar":u"الومينيوم","cs":u"hliník","fi":u"alumiini","ja":u"アルミカウム","es":u"alumínio"},
'PROTON_NUMBER': 13, 'DESC':{"cs":u"měkký stříbrošedý kov","en":u"soft silver-grey metal"},
'ROW': 3, },
'Si': { 'EN': 1.91, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 28.0855, 'NAME_LAT': u'silicium', 'COLUMN': 14, 'ATOM_SYMBOL': u'Si', 'ORBITALS': '1s2 2s2 2p6 3s2 3p2',
'OX_NUMBERS': [4, 2, -4], 'NAMES':{"ru":u"кремний","fr":u"silicium","en":u"silicon","nl":u"silicium ","pt":u"Silício","de":u"silizium","tr":u"silisyum","sv":u"kisel","ar":u"سيلكون","cs":u"křemík","fi":u"pii","ja":u"ヶィ素","es":u"silicio"},
'PROTON_NUMBER': 14, 'DESC':{"cs":u"šedý tvrdý a křehký polokov","en":u"gray hard and brittle semimetal"},
'ROW': 3, },
'P': { 'EN': 2.19, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 30.973761, 'NAME_LAT': u'phosphorus', 'COLUMN': 15, 'ATOM_SYMBOL': u'P', 'ORBITALS': '1s2 2s2 2p6 3s2 3p3',
'OX_NUMBERS': [5, 3, -3], 'NAMES':{"ru":u"фосфор","fr":u"phosphore","en":u"phosphorus","nl":u"fosfor","pt":u"Fósforo","de":u"phosphor","tr":u"fosfor","sv":u"fosfor","ar":u"فوسفور","cs":u"fosfor","fi":u"fosfori","ja":u"リン","es":u"fósforo"},
'PROTON_NUMBER': 15, 'DESC':{"cs":u"bílá, červená a černá modifikace","en":u"white, red and black modification"},
'ROW': 3, },
'S': { 'EN': 2.58, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 32.065, 'NAME_LAT': u'sulphurium', 'COLUMN': 16, 'ATOM_SYMBOL': u'S', 'ORBITALS': '1s2 2s2 2p6 3s2 3p4',
'OX_NUMBERS': [6, 4, 2, -2], 'NAMES':{"ru":u"сера","fr":u"soufre","en":u"sulphur","nl":u"zwavel","pt":u"Enxôfre","de":u"schwefel","tr":u"kükürt","sv":u"svavel","ar":u"كبريت","cs":u"síra","fi":u"rikki","ja":u"硫黄","es":u"azufre"},
'PROTON_NUMBER': 16, 'DESC':{"cs":u"žlutá krystalická látka","en":u"yellow crystalline substance"},
'ROW': 3, },
'Cl': { 'EN': 3.16, 'group':{"cs":u"halogeny","en":u"halogens","pt":u"halogéneos"},
'ATOM_WEIGHT': 35.453, 'NAME_LAT': u'chlorium', 'COLUMN': 17, 'ATOM_SYMBOL': u'Cl', 'ORBITALS': '1s2 2s2 2p6 3s2 3p5',
'OX_NUMBERS': [7, 5, 3, 1, -1], 'NAMES':{"ru":u"хлор","fr":u"chlore","en":u"chlorine","nl":u"chloor","pt":u"Cloro","de":u"chlor","tr":u"klor","sv":u"klor","ar":u"كلور","cs":u"chlor","fi":u"kloori","ja":u"塩素","es":u"cloro"},
'PROTON_NUMBER': 17, 'DESC':{"cs":u"reaktivní žlutozelený plyn","en":u"reactive siskin-green gas"},
'ROW': 3, },
'Ar': { 'EN': 0.0, 'group':{"cs":u"inertní plyny","en":u"inert-gases","pt":u"gases inertes"},
'ATOM_WEIGHT': 39.948, 'NAME_LAT': u'argon', 'COLUMN': 18, 'ATOM_SYMBOL': u'Ar', 'ORBITALS': '1s2 2s2 2p6 3s2 3p6',
'OX_NUMBERS': [], 'NAMES':{"ru":u"аргон","fr":u"argon","en":u"argon","nl":u"argon","pt":u"Argônio","de":u"argon","tr":u"argon","sv":u"argon","ar":u"أرجون","cs":u"argon","fi":u"argon","ja":u"アルゴン","es":u"argón"},
'PROTON_NUMBER': 18, 'DESC':{"cs":u"bezbarvý inertní plyn","en":u"colourless inert gas"},
'ROW': 3, },
'K': { 'EN': 0.82, 'group':{"cs":u"alkalické kovy","en":u"alkali-metals","pt":u"metais alcalinos"},
'ATOM_WEIGHT': 39.0983, 'NAME_LAT': u'kalium', 'COLUMN': 1, 'ATOM_SYMBOL': u'K', 'ORBITALS': 'Ar 4s1',
'OX_NUMBERS': [1], 'NAMES':{"ru":u"калий","fr":u"potassium","en":u"potassium","nl":u"kalium","pt":u"Potássio","de":u"kalium","tr":u"potasyum","sv":u"kalium","ar":u"بوتاسيوم","cs":u"draslík","fi":u"kalium","ja":u"カリウム","es":u"potasio"},
'PROTON_NUMBER': 19, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 4, },
'Ca': { 'EN': 1.0, 'group':{"cs":u"kovy alkalických zemin","en":u"alkali-earth-metals","pt":u"metais alcalino-terrosos"},
'ATOM_WEIGHT': 40.078, 'NAME_LAT': u'calcium', 'COLUMN': 2, 'ATOM_SYMBOL': u'Ca', 'ORBITALS': 'Ar 4s2',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"кальций","fr":u"calcium","en":u"calcium","nl":u"calcium","pt":u"Cálcio","de":u"kalzium","tr":u"kalsiyum","sv":u"kalcium","ar":u"كلسيوم","cs":u"vápník","fi":u"kalsium","ja":u"カルシウム","es":u"calcio"},
'PROTON_NUMBER': 20, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 4, },
'Sc': { 'EN': 1.36, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 44.95591, 'NAME_LAT': u'scandium', 'COLUMN': 3, 'ATOM_SYMBOL': u'Sc', 'ORBITALS': 'Ar 3d1 4s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"скандий","fr":u"scandium","en":u"scandium","nl":u"scandium","pt":u"Escândio","de":u"skandium","tr":u"skandiyum","sv":u"skandium","ar":u"سكانديوم","cs":u"scandium","fi":u"skandium","ja":u"スカンジウム","es":u"escandio"},
'PROTON_NUMBER': 21, 'DESC':{"cs":u"","en":u""},
'ROW': 4, },
'Ti': { 'EN': 1.54, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 47.867, 'NAME_LAT': u'titanium', 'COLUMN': 4, 'ATOM_SYMBOL': u'Ti', 'ORBITALS': 'Ar 3d2 4s2',
'OX_NUMBERS': [4, 3, 2], 'NAMES':{"ru":u"титан","fr":u"titane","en":u"titanium","nl":u"titaan","pt":u"Titânio","de":u"titan","tr":u"titan","sv":u"titan","ar":u"تيتانيوم","cs":u"titan","fi":u"titaani","ja":u"チタン","es":u"titanio"},
'PROTON_NUMBER': 22, 'DESC':{"cs":u"tvrdý a lehký stříbrolesklý kov","en":u"hard and light silvery metal"},
'ROW': 4, },
'V': { 'EN': 1.63, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 50.9415, 'NAME_LAT': u'vanadium', 'COLUMN': 5, 'ATOM_SYMBOL': u'V', 'ORBITALS': 'Ar 3d3 4s2',
'OX_NUMBERS': [5, 4, 3, 2, 1, 0, -1, -3], 'NAMES':{"ru":u"ванадий","fr":u"vanadium","en":u"vanadium","nl":u"vanadium","pt":u"Vanádio","de":u"vanadium","tr":u"vanadyum","sv":u"vanadin","ar":u"فناديوم","cs":u"vanad","fi":u"vanadiini","ja":u"グオジウム","es":u"vanadio"},
'PROTON_NUMBER': 23, 'DESC':{"cs":u"tvrdý ocelově šedý kov","en":u"hard steel-grey metal"},
'ROW': 4, },
'Cr': { 'EN': 1.66, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 51.9961, 'NAME_LAT': u'chromium', 'COLUMN': 6, 'ATOM_SYMBOL': u'Cr', 'ORBITALS': 'Ar 3d5 4s1',
'OX_NUMBERS': [6, 5, 4, 3, 2, 1, 0, -1, -2], 'NAMES':{"ru":u"хром","fr":u"chrome","en":u"chromium","nl":u"chroom","pt":u"Crômio","de":u"chrom","tr":u"krom","sv":u"krom","ar":u"كروم","cs":u"chrom","fi":u"kromi","ja":u"クロム","es":u"cromo"},
'PROTON_NUMBER': 24, 'DESC':{"cs":u"tvrdý stříbrolesklý kov","en":u"hard silvery metal"},
'ROW': 4, },
'Mn': { 'EN': 1.55, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 54.938049, 'NAME_LAT': u'manganum', 'COLUMN': 7, 'ATOM_SYMBOL': u'Mn', 'ORBITALS': 'Ar 3d5 4s2',
'OX_NUMBERS': [7, 6, 5, 4, 3, 2, 1, 0, -1, -2, -3], 'NAMES':{"ru":u"марганец","fr":u"manganèse","en":u"manganese","nl":u"mangaan","pt":u"Manganês","de":u"mangan","tr":u"mangan","sv":u"mangan","ar":u"منجنيز","cs":u"mangan","fi":u"mangaani","ja":u"マンガン","es":u"manganesio"},
'PROTON_NUMBER': 25, 'DESC':{"cs":u"tvrdý a křehký stříbrolesklý kov","en":u"hard and brittle silvery metal"},
'ROW': 4, },
'Fe': { 'EN': 1.83, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 55.845, 'NAME_LAT': u'ferrum', 'COLUMN': 8, 'ATOM_SYMBOL': u'Fe', 'ORBITALS': 'Ar 3d6 4s2',
'OX_NUMBERS': [6, 4, 5, 3, 2, 1, 0, -1, -2], 'NAMES':{"ru":u"железо","fr":u"fer","en":u"iron","nl":u"ijzer","pt":u"Ferro","de":u"eisen","tr":u"demir","sv":u"järn","ar":u"حديد","cs":u"železo","fi":u"rauta","ja":u"鉄","es":u"hierro"},
'PROTON_NUMBER': 26, 'DESC':{"cs":u"stříbrolesklý kov","en":u"silvery metal"},
'ROW': 4, },
'Co': { 'EN': 1.88, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 58.9332, 'NAME_LAT': u'cobaltum', 'COLUMN': 9, 'ATOM_SYMBOL': u'Co', 'ORBITALS': 'Ar 3d7 4s2',
'OX_NUMBERS': [5, 4, 3, 2, 1, 0, -1], 'NAMES':{"ru":u"кобальт","fr":u"cobalt","en":u"cobalt","nl":u"kobalt","pt":u"Cobalto","de":u"kobalt","tr":u"kobalt","sv":u"kobolt","ar":u"كوبلت","cs":u"kobalt","fi":u"koboltti","ja":u"コグルエ","es":u"cobalto"},
'PROTON_NUMBER': 27, 'DESC':{"cs":u"tvrdý stříbrošedý kov","en":u"hard silver-grey metal"},
'ROW': 4, },
'Ni': { 'EN': 1.91, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 58.6934, 'NAME_LAT': u'niccolum', 'COLUMN': 10, 'ATOM_SYMBOL': u'Ni', 'ORBITALS': 'Ar 3d8 4s2',
'OX_NUMBERS': [4, 3, 2, 1, 0, -1], 'NAMES':{"ru":u"никель","fr":u"nickel","en":u"nickel","nl":u"nikkel","pt":u"Niquel","de":u"nickel","tr":u"nikel","sv":u"nickel","ar":u"نيكل","cs":u"nikl","fi":u"nikkeli","ja":u"カィケル","es":u"níquel"},
'PROTON_NUMBER': 28, 'DESC':{"cs":u"bílý kov","en":u"white metal"},
'ROW': 4, },
'Cu': { 'EN': 1.9, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 63.546, 'NAME_LAT': u'cuprum', 'COLUMN': 11, 'ATOM_SYMBOL': u'Cu', 'ORBITALS': 'Ar 3d10 4s1',
'OX_NUMBERS': [4, 3, 2, 1], 'NAMES':{"ru":u"медь","fr":u"cuivre","en":u"copper","nl":u"koper","pt":u"Cobre","de":u"kupfer","tr":u"bakır","sv":u"koppar","ar":u"نحاس","cs":u"měď","fi":u"kupari","ja":u"銅","es":u"cobre"},
'PROTON_NUMBER': 29, 'DESC':{"cs":u"měkký načervenalý kov","en":u"soft blackish metal"},
'ROW': 4, },
'Zn': { 'EN': 1.65, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 65.39, 'NAME_LAT': u'zincum', 'COLUMN': 12, 'ATOM_SYMBOL': u'Zn', 'ORBITALS': 'Ar 3d10 4s2',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"цинк","fr":u"zinc","en":u"zinc","nl":u"zink","pt":u"Zinco","de":u"zink","tr":u"çinko","sv":u"zink","ar":u"خارصين","cs":u"zinek","fi":u"sinkki","ja":u"亜鉛","es":u"zinc"},
'PROTON_NUMBER': 30, 'DESC':{"cs":u"křehký modrobílý kov","en":u"brittle blue-white metal"},
'ROW': 4, },
'Ga': { 'EN': 1.81, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 69.723, 'NAME_LAT': u'gallium', 'COLUMN': 13, 'ATOM_SYMBOL': u'Ga', 'ORBITALS': 'Ar 3d10 4s2 4p1',
'OX_NUMBERS': [3, 2, 1], 'NAMES':{"ru":u"галлий","fr":u"gallium","en":u"gallium","nl":u"gallium","pt":u"Gálio","de":u"gallium","tr":u"galyum","sv":u"gallium","ar":u"جاليوم","cs":u"galium","fi":u"gallium","ja":u"ガリウム","es":u"galio"},
'PROTON_NUMBER': 31, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 4, },
'Ge': { 'EN': 2.01, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 72.64, 'NAME_LAT': u'germanium', 'COLUMN': 14, 'ATOM_SYMBOL': u'Ge', 'ORBITALS': 'Ar 3d10 4s2 4p2',
'OX_NUMBERS': [4, 2], 'NAMES':{"ru":u"германий","fr":u"germanium","en":u"germanium","nl":u"germanium","pt":u"Germânio","de":u"germanium","tr":u"germanyum","sv":u"germanium","ar":u"جرمانيوم","cs":u"germanium","fi":u"germanium","ja":u"ゲルマカウム","es":u"germánio"},
'PROTON_NUMBER': 32, 'DESC':{"cs":u"lesklý šedobílý polokov","en":u"glossy off-white semimetal"},
'ROW': 4, },
'As': { 'EN': 2.18, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 74.9216, 'NAME_LAT': u'arsenicum', 'COLUMN': 15, 'ATOM_SYMBOL': u'As', 'ORBITALS': 'Ar 3d10 4s2 4p3',
'OX_NUMBERS': [5, 3, -3], 'NAMES':{"ru":u"мышъяк","fr":u"arsenic","en":u"arsenic","nl":u"arseen","pt":u"Arsênio","de":u"arsen","tr":u"arsenik","sv":u"arsenik","ar":u"زرنيخ","cs":u"arsen","fi":u"arseeni","ja":u"ヒ素","es":u"arsénico"},
'PROTON_NUMBER': 33, 'DESC':{"cs":u"lehký polokov","en":u"light semimetal"},
'ROW': 4, },
'Se': { 'EN': 2.55, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 78.96, 'NAME_LAT': u'selenium', 'COLUMN': 16, 'ATOM_SYMBOL': u'Se', 'ORBITALS': 'Ar 3d10 4s2 4p4',
'OX_NUMBERS': [6, 4, -2], 'NAMES':{"ru":u"селен","fr":u"sélénium","en":u"selenium","nl":u"selenium","pt":u"Selênio","de":u"selen","tr":u"selenyum","sv":u"selen","ar":u"سيلينيوم","cs":u"selen","fi":u"seleeni","ja":u"セレン","es":u"selenio"},
'PROTON_NUMBER': 34, 'DESC':{"cs":u"lesklý černošedý nekov","en":u"glossy black-grey nonmetal"},
'ROW': 4, },
'Br': { 'EN': 2.96, 'group':{"cs":u"halogeny","en":u"halogens","pt":u"halogéneos"},
'ATOM_WEIGHT': 79.904, 'NAME_LAT': u'bromium', 'COLUMN': 17, 'ATOM_SYMBOL': u'Br', 'ORBITALS': 'Ar 3d10 4s2 4p5',
'OX_NUMBERS': [7, 5, 3, 1, -1], 'NAMES':{"ru":u"бром","fr":u"brome","en":u"bromine","nl":u"broom","pt":u"Bromo","de":u"brom","tr":u"brom","sv":u"brom","ar":u"بروم","cs":u"brom","fi":u"bromi","ja":u"臭素","es":u"bromo"},
'PROTON_NUMBER': 35, 'DESC':{"cs":u"reaktivní tmavě fialová kapalina","en":u"reactive deep violet liquid"},
'ROW': 4, },
'Kr': { 'EN': 0.0, 'group':{"cs":u"inertní plyny","en":u"inert-gases","pt":u"gases inertes"},
'ATOM_WEIGHT': 83.8, 'NAME_LAT': u'krypton', 'COLUMN': 18, 'ATOM_SYMBOL': u'Kr', 'ORBITALS': 'Ar 3d10 4s2 4p6',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"криптон","fr":u"krypton","en":u"krypton","nl":u"krypton","pt":u"Criptônio","de":u"krypton","tr":u"kripton","sv":u"krypton","ar":u"كربتون","cs":u"krypton","fi":u"krypton","ja":u"クリシエン","es":u"criptón"},
'PROTON_NUMBER': 36, 'DESC':{"cs":u"bezbarvý inertní plyn","en":u"colourless inert gas"},
'ROW': 4, },
'Rb': { 'EN': 0.82, 'group':{"cs":u"alkalické kovy","en":u"alkali-metals","pt":u"metais alcalinos"},
'ATOM_WEIGHT': 85.4678, 'NAME_LAT': u'rubidium', 'COLUMN': 1, 'ATOM_SYMBOL': u'Rb', 'ORBITALS': 'Kr 5s1',
'OX_NUMBERS': [1], 'NAMES':{"ru":u"рубидий","fr":u"rubidium","en":u"rubidium","nl":u"rubidium","pt":u"Rubidio","de":u"rubidium","tr":u"rubidyum","sv":u"rubidium","ar":u"روبيديوم","cs":u"rubidium","fi":u"rubidium","ja":u"ルコジウム","es":u"rubídio"},
'PROTON_NUMBER': 37, 'DESC':{"cs":u"reaktivní měkký a lehký stříbrolesklý kov","en":u"reactive soft and light silvery metal"},
'ROW': 5, },
'Sr': { 'EN': 0.95, 'group':{"cs":u"kovy alkalických zemin","en":u"alkali-earth-metals","pt":u"metais alcalino-terrosos"},
'ATOM_WEIGHT': 87.62, 'NAME_LAT': u'strontium', 'COLUMN': 2, 'ATOM_SYMBOL': u'Sr', 'ORBITALS': 'Kr 5s2',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"стронций","fr":u"strontium","en":u"strontium","nl":u"strontium","pt":u"Estrôncio","de":u"strontium","tr":u"stronsiyum","sv":u"strontium","ar":u"سترانشيوم","cs":u"stroncium","fi":u"strontium","ja":u"スエロンチウム","es":u"estroncio"},
'PROTON_NUMBER': 38, 'DESC':{"cs":u"stříbrolesklý kov","en":u"silvery metal"},
'ROW': 5, },
'Y': { 'EN': 1.22, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 88.90585, 'NAME_LAT': u'yttrium', 'COLUMN': 3, 'ATOM_SYMBOL': u'Y', 'ORBITALS': 'Kr 4d1 5s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"иттрий","fr":u"yttrium","en":u"yttrium","nl":u"yttrium","pt":u"Itrio","de":u"yttrium","tr":u"İtriyum","sv":u"yttrium","ar":u"يتريوم","cs":u"yttrium","fi":u"yttrium","ja":u"イィエリウム","es":u"itrio"},
'PROTON_NUMBER': 39, 'DESC':{"cs":u"","en":u""},
'ROW': 5, },
'Zr': { 'EN': 1.33, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 91.224, 'NAME_LAT': u'zirconium', 'COLUMN': 4, 'ATOM_SYMBOL': u'Zr', 'ORBITALS': 'Kr 4d2 5s2',
'OX_NUMBERS': [4, 3, 2, 1], 'NAMES':{"ru":u"цирконий","fr":u"zirconium","en":u"zirconium","nl":u"zirkonium","pt":u"Xircônio","de":u"zirkonium","tr":u"zirkonyum","sv":u"zirkonium","ar":u"زيركونيوم","cs":u"zirkon","fi":u"zirkonium","ja":u"ジルコカウム","es":u"circonio"},
'PROTON_NUMBER': 40, 'DESC':{"cs":u"látka stříbrošedý kov","en":u"substance silver-grey metal"},
'ROW': 5, },
'Nb': { 'EN': 1.6, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 92.90638, 'NAME_LAT': u'niobium', 'COLUMN': 5, 'ATOM_SYMBOL': u'Nb', 'ORBITALS': 'Kr 4d4',
'OX_NUMBERS': [5, 4, 3, 2, 1, -1], 'NAMES':{"ru":u"ниобий","fr":u"niobium","en":u"niobium","nl":u"niobium","pt":u"Nióbio","de":u"niob","tr":u"niobyum","sv":u"niob","ar":u"نيوبيوم","cs":u"niob","fi":u"niobium","ja":u"カオザ","es":u"niobio"},
'PROTON_NUMBER': 41, 'DESC':{"cs":u"","en":u""},
'ROW': 5, },
'Mo': { 'EN': 2.16, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 95.94, 'NAME_LAT': u'molybdenum', 'COLUMN': 6, 'ATOM_SYMBOL': u'Mo', 'ORBITALS': 'Kr 4d5 5s1',
'OX_NUMBERS': [6, 5, 4, 3, 2, 1, 0, -1, -2], 'NAMES':{"ru":u"молибден","fr":u"molybdène","en":u"molybdenum","nl":u"molybdeen","pt":u"Molibdênio","de":u"molybdän","tr":u"molibden","sv":u"molybden","ar":u"مولبيدنيوم","cs":u"molybden","fi":u"molybdeeni","ja":u"モリザェン","es":u"molibdeno"},
'PROTON_NUMBER': 42, 'DESC':{"cs":u"stříbrolesklý kov","en":u"silvery metal"},
'ROW': 5, },
'Tc': { 'EN': 1.9, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 98.9063, 'NAME_LAT': u'technetium', 'COLUMN': 7, 'ATOM_SYMBOL': u'Tc', 'ORBITALS': 'Kr 4d6 5s1',
'OX_NUMBERS': [7, 6, 5, 4, 3, 2, 1, 0, -1, -3], 'NAMES':{"ru":u"технеций","fr":u"technétium","en":u"technetium","nl":u"technetium","pt":u"Tecnécio","de":u"technetium","tr":u"teknesyum","sv":u"teknetium","ar":u"تكنيتيوم","cs":u"technecium","fi":u"teknetium","ja":u"ウクキチウム","es":u"tecnecio"},
'PROTON_NUMBER': 43, 'DESC':{"cs":u"","en":u""},
'ROW': 5, },
'Ru': { 'EN': 2.2, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 101.07, 'NAME_LAT': u'ruthenium', 'COLUMN': 8, 'ATOM_SYMBOL': u'Ru', 'ORBITALS': 'Kr 4d7 5s1',
'OX_NUMBERS': [8, 7, 6, 5, 4, 3, 2, 1, 0, -2], 'NAMES':{"ru":u"рутений","fr":u"ruthénium","en":u"ruthenium","nl":u"ruthenium","pt":u"Rutênio","de":u"ruthenium","tr":u"rutenyum","sv":u"rutenium","ar":u"روتينيوم","cs":u"ruthenium","fi":u"rutenium","ja":u"ルウカウム","es":u"rutenio"},
'PROTON_NUMBER': 44, 'DESC':{"cs":u"šedý a tvrdý ušlechtilý kov","en":u"gray and hard noble metal"},
'ROW': 5, },
'Rh': { 'EN': 2.28, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 102.9055, 'NAME_LAT': u'rhodium', 'COLUMN': 9, 'ATOM_SYMBOL': u'Rh', 'ORBITALS': 'Kr 4d8 5s1',
'OX_NUMBERS': [6, 5, 4, 3, 2, 1, 0, -1], 'NAMES':{"ru":u"родий","fr":u"rhodium","en":u"rhodium","nl":u"rhodium","pt":u"Ródio","de":u"rhodium","tr":u"rodyum","sv":u"rodium","ar":u"روديوم","cs":u"rhodium","fi":u"rodium","ja":u"ロジウム","es":u"rodio"},
'PROTON_NUMBER': 45, 'DESC':{"cs":u"bezbarvý tažný kov","en":u"colourless draw metal"},
'ROW': 5, },
'Pd': { 'EN': 2.2, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 106.42, 'NAME_LAT': u'palladium', 'COLUMN': 10, 'ATOM_SYMBOL': u'Pd', 'ORBITALS': 'Kr 4d10',
'OX_NUMBERS': [4, 3, 2, 0], 'NAMES':{"ru":u"палладий","fr":u"palladium","en":u"palladium","nl":u"palladium","pt":u"Paládio","de":u"palladium","tr":u"palladyum","sv":u"palladium","ar":u"بلاديوم","cs":u"palladium","fi":u"palladium","ja":u"ケラジウム","es":u"paladio"},
'PROTON_NUMBER': 46, 'DESC':{"cs":u"kujný a tažný stříbrolesklý kov","en":u"ductile and draw metal"},
'ROW': 5, },
'Ag': { 'EN': 1.93, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 107.8682, 'NAME_LAT': u'argentum', 'COLUMN': 11, 'ATOM_SYMBOL': u'Ag', 'ORBITALS': 'Kr 4d10 5s1',
'OX_NUMBERS': [3, 2, 1], 'NAMES':{"ru":u"серебро","fr":u"argent","en":u"silver","nl":u"zilver","pt":u"Prata","de":u"silber","tr":u"gümüş","sv":u"silver","ar":u"فضة","cs":u"stříbro","fi":u"hopea","ja":u"銀","es":u"plata"},
'PROTON_NUMBER': 47, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 5, },
'Cd': { 'EN': 1.69, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 112.411, 'NAME_LAT': u'cadmium', 'COLUMN': 12, 'ATOM_SYMBOL': u'Cd', 'ORBITALS': 'Kr 4d10 5s2',
'OX_NUMBERS': [2, 1], 'NAMES':{"ru":u"кадмий","fr":u"cadmium","en":u"cadmium","nl":u"cadmium","pt":u"Cádmio","de":u"kadmium","tr":u"kadmiyum","sv":u"kadmium","ar":u"كادميوم","cs":u"kadmium","fi":u"kadmium","ja":u"カォミウム","es":u"cadmio"},
'PROTON_NUMBER': 48, 'DESC':{"cs":u"bezbarvý tažný kov","en":u"colourless draw metal"},
'ROW': 5, },
'In': { 'EN': 1.78, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 114.818, 'NAME_LAT': u'indium', 'COLUMN': 13, 'ATOM_SYMBOL': u'In', 'ORBITALS': 'Kr 4d10 5s2 5p1',
'OX_NUMBERS': [3, 2, 1], 'NAMES':{"ru":u"индий","fr":u"indium","en":u"indium","nl":u"indium","pt":u"índio","de":u"indium","tr":u"İndiyum","sv":u"indium","ar":u"انديوم","cs":u"indium","fi":u"indium","ja":u"インジウム","es":u"indio"},
'PROTON_NUMBER': 49, 'DESC':{"cs":u"","en":u""},
'ROW': 5, },
'Sn': { 'EN': 1.96, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 118.71, 'NAME_LAT': u'stannum', 'COLUMN': 14, 'ATOM_SYMBOL': u'Sn', 'ORBITALS': 'Kr 4d10 5s2 5p2',
'OX_NUMBERS': [4, 2], 'NAMES':{"ru":u"олово","fr":u"étain","en":u"tin","nl":u"tin","pt":u"Estanho","de":u"zinn","tr":u"kalay","sv":u"tenn","ar":u"قصدير","cs":u"cín","fi":u"tina","ja":u"スズ","es":u"estaño"},
'PROTON_NUMBER': 50, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 5, },
'Sb': { 'EN': 2.05, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 121.76, 'NAME_LAT': u'stibium', 'COLUMN': 15, 'ATOM_SYMBOL': u'Sb', 'ORBITALS': 'Kr 4d10 5s2 5p3',
'OX_NUMBERS': [5, 3, -3], 'NAMES':{"ru":u"сурьма","fr":u"antimoine","en":u"antimony","nl":u"antimoon","pt":u"Actimônio","de":u"antimon","tr":u"antimon","sv":u"antimon","ar":u"انتيمون","cs":u"antimon","fi":u"antimoni","ja":u"アンチモン アンチモカ","es":u"antimonio"},
'PROTON_NUMBER': 51, 'DESC':{"cs":u"stříbrolesklý křehký polokov","en":u"silvery brittle semimetal"},
'ROW': 5, },
'Te': { 'EN': 2.1, 'group':{"cs":u"nekovy","en":u"non-metals","pt":u"não metais"},
'ATOM_WEIGHT': 127.6, 'NAME_LAT': u'tellurium', 'COLUMN': 16, 'ATOM_SYMBOL': u'Te', 'ORBITALS': 'Kr 4d10 5s2 5p4',
'OX_NUMBERS': [6, 4, 2, -2], 'NAMES':{"ru":u"теллур","fr":u"tellure","en":u"tellurium","nl":u"telluur","pt":u"Telúrio","de":u"tellur","tr":u"tellur","sv":u"tellur","ar":u"تيلوريوم","cs":u"tellur","fi":u"telluuri","ja":u"ウルル","es":u"teluro"},
'PROTON_NUMBER': 52, 'DESC':{"cs":u"stříbrolesklý polokov","en":u"silvery semimetal"},
'ROW': 5, },
'I': { 'EN': 2.66, 'group':{"cs":u"halogeny","en":u"halogens","pt":u"halogéneos"},
'ATOM_WEIGHT': 126.90447, 'NAME_LAT': u'iodium', 'COLUMN': 17, 'ATOM_SYMBOL': u'I', 'ORBITALS': 'Kr 4d10 5s2 5p5',
'OX_NUMBERS': [7, 5, 3, 1, -1], 'NAMES':{"ru":u"йод","fr":u"iode","en":u"iodine","nl":u"jood","pt":u"Iôdo","de":u"iod","tr":u"İyod","sv":u"jod","ar":u"يود","cs":u"jod","fi":u"jodi","ja":u"ヨウ素","es":u"yodo"},
'PROTON_NUMBER': 53, 'DESC':{"cs":u"reaktivní tmavě fialová pevná látka","en":u"reactive deep violet solid (substance)"},
'ROW': 5, },
'Xe': { 'EN': 2.6, 'group':{"cs":u"inertní plyny","en":u"inert-gases","pt":u"gases inertes"},
'ATOM_WEIGHT': 131.293, 'NAME_LAT': u'xenon', 'COLUMN': 18, 'ATOM_SYMBOL': u'Xe', 'ORBITALS': 'Kr 4d10 5s2 5p6',
'OX_NUMBERS': [2, 4, 6, 8], 'NAMES':{"ru":u"ксенон","fr":u"xénon","en":u"xenon","nl":u"xenon","pt":u"Xenônio","de":u"xenon","tr":u"ksenon","sv":u"xenon","ar":u"إكسينون","cs":u"xenon","fi":u"ksenon","ja":u"キセギン","es":u"xenón"},
'PROTON_NUMBER': 54, 'DESC':{"cs":u"bezbarvý inertní plyn","en":u"colourless inert gas"},
'ROW': 5, },
'Cs': { 'EN': 0.79, 'group':{"cs":u"alkalické kovy","en":u"alkali-metals","pt":u"metais alcalinos"},
'ATOM_WEIGHT': 132.90545, 'NAME_LAT': u'caesium', 'COLUMN': 1, 'ATOM_SYMBOL': u'Cs', 'ORBITALS': 'Xe 6s1',
'OX_NUMBERS': [1], 'NAMES':{"ru":u"цезий","fr":u"caesium","en":u"cesium","nl":u"cesium","pt":u"Césio","de":u"zäsium","tr":u"sezyum","sv":u"cesium","ar":u"سيزيوم","cs":u"cesium","fi":u"cesium","ja":u"セシウム","es":u"cesio"},
'PROTON_NUMBER': 55, 'DESC':{"cs":u"reaktivní měkký a lehký stříbrolesklý kov","en":u"reactive soft and light silvery metal"},
'ROW': 6, },
'Ba': { 'EN': 0.89, 'group':{"cs":u"kovy alkalických zemin","en":u"alkali-earth-metals","pt":u"metais alcalino-terrosos"},
'ATOM_WEIGHT': 137.237, 'NAME_LAT': u'barium', 'COLUMN': 2, 'ATOM_SYMBOL': u'Ba', 'ORBITALS': 'Xe 6s2',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"барий","fr":u"baryum","en":u"barium","nl":u"barium","pt":u"Bário","de":u"barium","tr":u"baryum","sv":u"barium","ar":u"باريوم","cs":u"barium","fi":u"barium","ja":u"グリウム","es":u"bario"},
'PROTON_NUMBER': 56, 'DESC':{"cs":u"měkký stříbrolesklý kov","en":u"soft silvery metal"},
'ROW': 6, },
'La': { 'EN': 1.1, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 138.9055, 'NAME_LAT': u'lanthanum', 'COLUMN': 101, 'ATOM_SYMBOL': u'La', 'ORBITALS': 'Xe 5d1 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"лантан","fr":u"lanthane","en":u"lanthanum","nl":u"lanthaan","pt":u"Lantânio","de":u"lanthan","tr":u"lantan","sv":u"lantan","ar":u"لنثانوم","cs":u"lanthan","fi":u"lantaani","ja":u"ランタン","es":u"lantano"},
'PROTON_NUMBER': 57, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Ce': { 'EN': 1.12, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 140.116, 'NAME_LAT': u'cerium', 'COLUMN': 102, 'ATOM_SYMBOL': u'Ce', 'ORBITALS': 'Xe 4f1 5d1 6s2',
'OX_NUMBERS': [4, 3], 'NAMES':{"ru":u"церий","fr":u"cérium","en":u"cerium","nl":u"cerium","de":u"zer","tr":u"seryum","sv":u"cerium","ar":u"سيريوم","cs":u"cer","fi":u"cerium","ja":u"セリウム","es":u"cério"},
'PROTON_NUMBER': 58, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Pr': { 'EN': 1.13, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 140.90765, 'NAME_LAT': u'praseodymium', 'COLUMN': 103, 'ATOM_SYMBOL': u'Pr', 'ORBITALS': 'Xe 4f3 6s2',
'OX_NUMBERS': [4, 3], 'NAMES':{"ru":u"празеодий","fr":u"praséodyme","en":u"praseodymium","nl":u"praseodymium","de":u"praseodym","tr":u"praseodim","sv":u"praseodym","ar":u"براسوديميوم","cs":u"praseodym","fi":u"praseodyymi","ja":u"シラセオジム","es":u"prosedímio"},
'PROTON_NUMBER': 59, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Nd': { 'EN': 1.14, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 144.24, 'NAME_LAT': u'neodymium', 'COLUMN': 104, 'ATOM_SYMBOL': u'Nd', 'ORBITALS': 'Xe 4f4 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"ниодийий","fr":u"néodyme","en":u"neodymium","nl":u"neodymium","de":u"neodym","tr":u"neodim","sv":u"neodym","ar":u"نيودميوم","cs":u"neodym","fi":u"neodyymi","ja":u"キオジム","es":u"neodímio"},
'PROTON_NUMBER': 60, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Pm': { 'EN': 1.13, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 146.9151, 'NAME_LAT': u'promethium', 'COLUMN': 105, 'ATOM_SYMBOL': u'Pm', 'ORBITALS': 'Xe 4f5 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"прометий","fr":u"prométhium","en":u"promethium","nl":u"promethium","de":u"promethium","tr":u"prometyum","sv":u"prometium","ar":u"بروميثيوم","cs":u"promethium","fi":u"prometium","ja":u"シロメチウム","es":u"promécio"},
'PROTON_NUMBER': 61, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Sm': { 'EN': 1.17, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 150.36, 'NAME_LAT': u'samarium', 'COLUMN': 106, 'ATOM_SYMBOL': u'Sm', 'ORBITALS': 'Xe 4f6 6s2',
'OX_NUMBERS': [3, 2], 'NAMES':{"ru":u"самарий","fr":u"samarium","en":u"samarium","nl":u"samarium","de":u"samarium","tr":u"samaryum","sv":u"samarium","ar":u"ساماريوم","cs":u"samarium","fi":u"samarium","ja":u"サマリウム","es":u"samário"},
'PROTON_NUMBER': 62, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Eu': { 'EN': 1.2, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 151.964, 'NAME_LAT': u'europium', 'COLUMN': 107, 'ATOM_SYMBOL': u'Eu', 'ORBITALS': 'Xe 4f7 6s2',
'OX_NUMBERS': [3, 2], 'NAMES':{"ru":u"европий","fr":u"europium","en":u"europium","nl":u"europium","de":u"europium","tr":u"europyum","sv":u"europium","ar":u"يروبيوم","cs":u"europium","fi":u"europium","ja":u"ユウロゴウム","es":u"európio"},
'PROTON_NUMBER': 63, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Gd': { 'EN': 1.2, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 157.25, 'NAME_LAT': u'gadolinium', 'COLUMN': 108, 'ATOM_SYMBOL': u'Gd', 'ORBITALS': 'Xe 4f7 5d1 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"гадолиний","fr":u"gadolinium","en":u"gadolinium","nl":u"gadolinium","de":u"gadolinium","tr":u"gadolinyum","sv":u"gadolinium","ar":u"جدولينيوم","cs":u"gadolinium","fi":u"gadolinium","ja":u"ガォリカウム","es":u"gadolíneo"},
'PROTON_NUMBER': 64, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Tb': { 'EN': 1.1, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 158.92534, 'NAME_LAT': u'terbium', 'COLUMN': 109, 'ATOM_SYMBOL': u'Tb', 'ORBITALS': 'Xe 4f9 6s2',
'OX_NUMBERS': [4, 3], 'NAMES':{"ru":u"тербий","fr":u"terbium","en":u"terbium","nl":u"terbium","de":u"terbium","tr":u"terbiyum","sv":u"terbium","ar":u"تربيوم","cs":u"terbium","fi":u"terbium","ja":u"ウルコウム","es":u"térbio"},
'PROTON_NUMBER': 65, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Dy': { 'EN': 1.22, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 162.5, 'NAME_LAT': u'dysprosium', 'COLUMN': 110, 'ATOM_SYMBOL': u'Dy', 'ORBITALS': 'Xe 4f10 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"диспрозий","fr":u"dysprosium","en":u"dysprosium","nl":u"dysprosium","de":u"dysprosium","tr":u"disprosyum","sv":u"dysprosium","ar":u"ديسبروسيوم","cs":u"dysprosium","fi":u"dysprosium","ja":u"ジスシロシウム","es":u"disprósio"},
'PROTON_NUMBER': 66, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Ho': { 'EN': 1.23, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 164.93032, 'NAME_LAT': u'holmium', 'COLUMN': 111, 'ATOM_SYMBOL': u'Ho', 'ORBITALS': 'Xe 4f11 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"голъмий","fr":u"holmium","en":u"holmium","nl":u"holmium","de":u"holmium","tr":u"holmiyum","sv":u"holmium","ar":u"هلميوم","cs":u"holmium","fi":u"holmium","ja":u"セルミウム","es":u"hólmio"},
'PROTON_NUMBER': 67, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Er': { 'EN': 1.24, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 167.259, 'NAME_LAT': u'erbium', 'COLUMN': 112, 'ATOM_SYMBOL': u'Er', 'ORBITALS': 'Xe 4f12 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"эрбий","fr":u"erbium","en":u"erbium","nl":u"erbium","de":u"erbium","tr":u"erbiyum","sv":u"erbium","ar":u"إربيوم","cs":u"erbium","fi":u"erbium","ja":u"エルコウム","es":u"érbio"},
'PROTON_NUMBER': 68, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Tm': { 'EN': 1.25, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 168.93421, 'NAME_LAT': u'thulium', 'COLUMN': 113, 'ATOM_SYMBOL': u'Tm', 'ORBITALS': 'Xe 4f13 6s2',
'OX_NUMBERS': [3, 2], 'NAMES':{"ru":u"тулий","fr":u"thulium","en":u"thulium","nl":u"thulium","de":u"thulium","tr":u"tulyum","sv":u"tulium","ar":u"ثليوم","cs":u"thulium","fi":u"tulium","ja":u"イリウム","es":u"túlio"},
'PROTON_NUMBER': 69, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Yb': { 'EN': 1.1, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 173.04, 'NAME_LAT': u'ytterbium', 'COLUMN': 114, 'ATOM_SYMBOL': u'Yb', 'ORBITALS': 'Xe 4f14 6s2',
'OX_NUMBERS': [3, 2], 'NAMES':{"ru":u"иттербий","fr":u"ytterbium","en":u"ytterbium","nl":u"ytterbium","de":u"ytterbium","tr":u"İtterbiyum","sv":u"ytterbium","ar":u"يتربيوم","cs":u"ytterbium","fi":u"ytterbium","ja":u"イィウルコウム","es":u"itérbio"},
'PROTON_NUMBER': 70, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Lu': { 'EN': 1.27, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 174.967, 'NAME_LAT': u'lutetium', 'COLUMN': 3, 'ATOM_SYMBOL': u'Lu', 'ORBITALS': 'Xe 4f14 5d1 6s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"лютеций","fr":u"lutécium","en":u"lutetium","nl":u"lutetium","de":u"lutetium","tr":u"lutesyum","sv":u"lutetium","ar":u"لوتيتيوم","cs":u"lutecium","fi":u"lutetium","ja":u"ルウチウム","es":u"lutécio"},
'PROTON_NUMBER': 71, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Hf': { 'EN': 1.3, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 178.49, 'NAME_LAT': u'hafnium', 'COLUMN': 4, 'ATOM_SYMBOL': u'Hf', 'ORBITALS': 'Xe 4f14 5d2 6s2',
'OX_NUMBERS': [4, 3, 1], 'NAMES':{"ru":u"гафний","fr":u"hafnium","en":u"hafnium","nl":u"hafnium","pt":u"Háfnio","de":u"hafnium","tr":u"hafniyum","sv":u"hafnium","ar":u"هفنيوم","cs":u"hafnium","fi":u"hafnium","ja":u"クサカウム","es":u"hafnio"},
'PROTON_NUMBER': 72, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Ta': { 'EN': 1.5, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 180.9479, 'NAME_LAT': u'tantalum', 'COLUMN': 5, 'ATOM_SYMBOL': u'Ta', 'ORBITALS': 'Xe 4f14 5d3 6s2',
'OX_NUMBERS': [5, 4, 3, 2, 1, -1], 'NAMES':{"ru":u"тантал","fr":u"tantale","en":u"tantalum","nl":u"tantaal","pt":u"Tantálio","de":u"tantal","tr":u"tantal","sv":u"tantal","ar":u"تنتالم","cs":u"tantal","fi":u"tantaali","ja":u"タンタル","es":u"tántalo"},
'PROTON_NUMBER': 73, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'W': { 'EN': 2.36, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 183.84, 'NAME_LAT': u'wolframium', 'COLUMN': 6, 'ATOM_SYMBOL': u'W', 'ORBITALS': 'Xe 4f14 5d4 6s2',
'OX_NUMBERS': [6, 5, 4, 3, 2, 0, -1, -2], 'NAMES':{"ru":u"вольфрам","fr":u"tungstène","en":u"tungsten","nl":u"wolfraam","pt":u"Tungstênio","de":u"wolfram","tr":u"volfram","sv":u"volfram","ar":u"تنجستين","cs":u"wolfram","fi":u"volframi","ja":u"タングスウン","es":u"wolframio"},
'PROTON_NUMBER': 74, 'DESC':{"cs":u"stříbrolesklý kov","en":u"silvery metal"},
'ROW': 6, },
'Re': { 'EN': 1.9, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 186.207, 'NAME_LAT': u'rhenium', 'COLUMN': 7, 'ATOM_SYMBOL': u'Re', 'ORBITALS': 'Xe 4f14 5d5 6s2',
'OX_NUMBERS': [7, 6, 5, 4, 3, 2, 1, 0, -1, -3], 'NAMES':{"ru":u"рений","fr":u"rhénium","en":u"rhenium","nl":u"rhenium","pt":u"Rênio","de":u"rhenium","tr":u"renyum","sv":u"rhenium","ar":u"رنيوم","cs":u"rhenium","fi":u"renium","ja":u"レカウム","es":u"renio"},
'PROTON_NUMBER': 75, 'DESC':{"cs":u"měkký kujný kov","en":u"soft ductile metal"},
'ROW': 6, },
'Os': { 'EN': 2.2, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 190.23, 'NAME_LAT': u'osmium', 'COLUMN': 8, 'ATOM_SYMBOL': u'Os', 'ORBITALS': 'Xe 4f14 5d6 6s2',
'OX_NUMBERS': [8, 6, 5, 4, 3, 2, 1, 0, -2], 'NAMES':{"ru":u"осмий","fr":u"osmium","en":u"osmium","nl":u"osmium","pt":u"Osmio","de":u"osmium","tr":u"osmiyum","sv":u"osmium","ar":u"ازميوم","cs":u"osmium","fi":u"osmium","ja":u"オスミウム","es":u"osmio"},
'PROTON_NUMBER': 76, 'DESC':{"cs":u"modrošedý kov","en":u"griseous metal"},
'ROW': 6, },
'Ir': { 'EN': 2.2, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 192.217, 'NAME_LAT': u'iridium', 'COLUMN': 9, 'ATOM_SYMBOL': u'Ir', 'ORBITALS': 'Xe 4f14 5d7 6s2',
'OX_NUMBERS': [6, 5, 4, 3, 2, 1, 0, -1], 'NAMES':{"ru":u"иридий","fr":u"iridium","en":u"iridium","nl":u"iridium","pt":u"Irídio","de":u"iridium","tr":u"İridyum","sv":u"iridium","ar":u"إريديوم","cs":u"iridium","fi":u"iridium","ja":u"イリジウム","es":u"iridio"},
'PROTON_NUMBER': 77, 'DESC':{"cs":u"bílý tvrdý a křehký kov","en":u"white hard and brittle metal"},
'ROW': 6, },
'Pt': { 'EN': 2.28, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 195.078, 'NAME_LAT': u'platinum', 'COLUMN': 10, 'ATOM_SYMBOL': u'Pt', 'ORBITALS': 'Xe 4f14 5d9 6s1',
'OX_NUMBERS': [6, 5, 4, 2, 0], 'NAMES':{"ru":u"платина","fr":u"platine","en":u"platinum","nl":u"platina ","pt":u"Platina","de":u"platin","tr":u"platin","sv":u"platina","ar":u"بلاتين","cs":u"platina","fi":u"platina","ja":u"白金","es":u"platino"},
'PROTON_NUMBER': 78, 'DESC':{"cs":u"stříbrolesklý kov","en":u"silvery metal"},
'ROW': 6, },
'Au': { 'EN': 2.54, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 196.96654, 'NAME_LAT': u'aurum', 'COLUMN': 11, 'ATOM_SYMBOL': u'Au', 'ORBITALS': 'Xe 4f14 5d10 6s1',
'OX_NUMBERS': [5, 3, 2, 1], 'NAMES':{"ru":u"золото","fr":u"or","en":u"gold","nl":u"goud","pt":u"Ouro","de":u"gold","tr":u"altın","sv":u"guld","ar":u"ذهب","cs":u"zlato","fi":u"kulta","ja":u"金","es":u"oro"},
'PROTON_NUMBER': 79, 'DESC':{"cs":u"měkký žlutý kov","en":u"soft yellow metal"},
'ROW': 6, },
'Hg': { 'EN': 2.0, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 200.59, 'NAME_LAT': u'hydrargyrum', 'COLUMN': 12, 'ATOM_SYMBOL': u'Hg', 'ORBITALS': 'Xe 4f14 5d10 6s2',
'OX_NUMBERS': [2, 1], 'NAMES':{"ru":u"ртуть","fr":u"mercure","en":u"mercury","nl":u"kwik, kwikzilver ","pt":u"Mercúrio","de":u"quecksilber","tr":u"civa","sv":u"kvicksilver","ar":u"زئبق","cs":u"rtuť","fi":u"elohopea","ja":u"ж ґйљђ","es":u"mercurio"},
'PROTON_NUMBER': 80, 'DESC':{"cs":u"stříbrolesklý kapalný kov","en":u"silvery liquid metal"},
'ROW': 6, },
'Tl': { 'EN': 2.04, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 204.3833, 'NAME_LAT': u'thallium', 'COLUMN': 13, 'ATOM_SYMBOL': u'Tl', 'ORBITALS': 'Xe 4f14 5d10 6s2 6p1',
'OX_NUMBERS': [3, 1], 'NAMES':{"ru":u"таллий","fr":u"thallium","en":u"thallium","nl":u"thallium","pt":u"Tálio","de":u"thallium","tr":u"talyum","sv":u"tallium","ar":u"ثاليوم","cs":u"thallium","fi":u"tallium","ja":u"タリウム","es":u"talio"},
'PROTON_NUMBER': 81, 'DESC':{"cs":u"měkký šedý kov","en":u"soft gray metal"},
'ROW': 6, },
'Pb': { 'EN': 2.33, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 207.2, 'NAME_LAT': u'plumbum', 'COLUMN': 14, 'ATOM_SYMBOL': u'Pb', 'ORBITALS': 'Xe 4f14 5d10 6s2 6p2',
'OX_NUMBERS': [4, 2], 'NAMES':{"ru":u"свинец","fr":u"plomb","en":u"lead","nl":u"lood","pt":u"Chumbo","de":u"blei","tr":u"kurşun","sv":u"bly","ar":u"رصاص","cs":u"olovo","fi":u"lyijy","ja":u"鉛","es":u"plomo"},
'PROTON_NUMBER': 82, 'DESC':{"cs":u"měkký šedý kov","en":u"soft gray metal"},
'ROW': 6, },
'Bi': { 'EN': 2.02, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 208.98038, 'NAME_LAT': u'bisemutum', 'COLUMN': 15, 'ATOM_SYMBOL': u'Bi', 'ORBITALS': 'Xe 4f14 5d10 6s2 6p3',
'OX_NUMBERS': [5, 3], 'NAMES':{"ru":u"висмут","fr":u"bismuth","en":u"bismuth","nl":u"bismut","pt":u"Bismuto","de":u"wismut","tr":u"bizmut","sv":u"vismut","ar":u"بزموث","cs":u"bismut","fi":u"vismutti","ja":u"コスマス","es":u"bismuto"},
'PROTON_NUMBER': 83, 'DESC':{"cs":u"lesklý narůžovělý kov","en":u"glossy light pink metal"},
'ROW': 6, },
'Po': { 'EN': 2.0, 'group':{"cs":u"ostatní kovy","en":u"other-metals","pt":u"outros metais"},
'ATOM_WEIGHT': 208.9824, 'NAME_LAT': u'polonium', 'COLUMN': 16, 'ATOM_SYMBOL': u'Po', 'ORBITALS': 'Xe 4f14 5d10 6s2 6p4',
'OX_NUMBERS': [6, 4, 2], 'NAMES':{"ru":u"полоний","fr":u"polonium","en":u"polonium","nl":u"polonium","pt":u"Polônio","de":u"polonium","tr":u"polonyum","sv":u"polonium","ar":u"بولونيوم","cs":u"polonium","fi":u"polonium","ja":u"ポロカウム","es":u"polonio"},
'PROTON_NUMBER': 84, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'At': { 'EN': 2.2, 'group':{"cs":u"halogeny","en":u"halogens","pt":u"halogéneos"},
'ATOM_WEIGHT': 209.9871, 'NAME_LAT': u'astatium', 'COLUMN': 17, 'ATOM_SYMBOL': u'At', 'ORBITALS': 'Xe 4f14 5d10 6s2 6p5',
'OX_NUMBERS': [7, 5, 3, 1, -1], 'NAMES':{"ru":u"астатин","fr":u"astate","en":u"astatine","nl":u"astaat","pt":u"Astato","de":u"astat","tr":u"asatatin","sv":u"astat","ar":u"استاتين","cs":u"astat","fi":u"astatiini","ja":u"アスタチン","es":u"astato"},
'PROTON_NUMBER': 85, 'DESC':{"cs":u"","en":u""},
'ROW': 6, },
'Rn': { 'EN': 0.0, 'group':{"cs":u"inertní plyny","en":u"inert-gases","pt":u"gases inertes"},
'ATOM_WEIGHT': 222.0176, 'NAME_LAT': u'radon', 'COLUMN': 18, 'ATOM_SYMBOL': u'Rn', 'ORBITALS': 'Xe 4f14 5d10 6s2 6p6',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"радон","fr":u"radon","en":u"radon","nl":u"radon","pt":u"Radônio","de":u"radon","tr":u"radon","sv":u"radon","ar":u"رادون","cs":u"radon","fi":u"radon","ja":u"ラォン","es":u"radón"},
'PROTON_NUMBER': 86, 'DESC':{"cs":u"bezbarvý radioaktivní inertní plyn","en":u"colourless radioactive inert gas"},
'ROW': 6, },
'Fr': { 'EN': 0.7, 'group':{"cs":u"alkalické kovy","en":u"alkali-metals","pt":u"metais alcalinos"},
'ATOM_WEIGHT': 223.0197, 'NAME_LAT': u'francium', 'COLUMN': 1, 'ATOM_SYMBOL': u'Fr', 'ORBITALS': 'Rd 7s1',
'OX_NUMBERS': [1], 'NAMES':{"ru":u"франций","fr":u"francium","en":u"francium","nl":u"francium","de":u"franzium","tr":u"fransiyum","sv":u"francium","ar":u"فرنسيوم","cs":u"francium","fi":u"frankium","ja":u"サランシウム","es":u"francio"},
'PROTON_NUMBER': 87, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Ra': { 'EN': 0.89, 'group':{"cs":u"kovy alkalických zemin","en":u"alkali-earth-metals","pt":u"metais alcalino-terrosos"},
'ATOM_WEIGHT': 226.0254, 'NAME_LAT': u'radium', 'COLUMN': 2, 'ATOM_SYMBOL': u'Ra', 'ORBITALS': 'Rd 7s2',
'OX_NUMBERS': [2], 'NAMES':{"ru":u"радий","fr":u"radium","en":u"radium","nl":u"radium","pt":u"Rádio","de":u"radium","tr":u"radyum","sv":u"radium","ar":u"راديوم","cs":u"radium","fi":u"radium","ja":u"ラジウム","es":u"radio"},
'PROTON_NUMBER': 88, 'DESC':{"cs":u"stříbrolesklý radioaktivní kov","en":u"silvery radioactive metal"},
'ROW': 7, },
'Ac': { 'EN': 1.1, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 227.0278, 'NAME_LAT': u'actinium', 'COLUMN': 101, 'ATOM_SYMBOL': u'Ac', 'ORBITALS': 'Rd 6d1 7s2',
'OX_NUMBERS': [3], 'NAMES':{"ru":u"актиний","fr":u"actinium","en":u"actinium","nl":u"actinium","de":u"aktinium","tr":u"aktinyum","sv":u"aktinium","ar":u"اكتنيوم","cs":u"actinium","fi":u"aktinium","ja":u"アクチカウム","es":u"actínio"},
'PROTON_NUMBER': 89, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Th': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 232.0381, 'NAME_LAT': u'thorium', 'COLUMN': 102, 'ATOM_SYMBOL': u'Th', 'OX_NUMBERS': [4, 3, 2], 'NAMES':{"ru":u"торий","fr":u"thorium","en":u"thorium","nl":u"thorium","de":u"thorium","tr":u"toryum","sv":u"torium","ar":u"ثوريوم","cs":u"thorium","fi":u"torium","ja":u"エリウム","es":u"tório"},
'PROTON_NUMBER': 90, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Pa': { 'EN': 1.5, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 231.03588, 'NAME_LAT': u'protactinium', 'COLUMN': 103, 'ATOM_SYMBOL': u'Pa', 'OX_NUMBERS': [5, 4, 3], 'NAMES':{"ru":u"протактиний","fr":u"protactinium","en":u"protactinium","nl":u"protactinium","de":u"protaktinium","tr":u"protaktinyum","sv":u"protaktinium","ar":u"بروتكتنيوم","cs":u"protactinium","fi":u"protaktinium","ja":u"シロエアクチカウム","es":u"protactínio"},
'PROTON_NUMBER': 91, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'U': { 'EN': 1.38, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 238.02891, 'NAME_LAT': u'uranium', 'COLUMN': 104, 'ATOM_SYMBOL': u'U', 'OX_NUMBERS': [6, 5, 4, 3], 'NAMES':{"ru":u"уран","fr":u"uranium","en":u"uranium","nl":u"uraan","pt":u"Urânio","de":u"uran","tr":u"uranyum","sv":u"uran","ar":u"يورانيوم","cs":u"uran","fi":u"uraani","ja":u"ウラン","es":u"uranio"},
'PROTON_NUMBER': 92, 'DESC':{"cs":u"těžký stříbrošedý radioaktivní kov","en":u"heavy silver-grey radioactive metal"},
'ROW': 7, },
'Np': { 'EN': 1.36, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 237.0482, 'NAME_LAT': u'neptunium', 'COLUMN': 105, 'ATOM_SYMBOL': u'Np', 'OX_NUMBERS': [7, 6, 5, 4, 3], 'NAMES':{"ru":u"нептуний","fr":u"neptunium","en":u"neptunium","nl":u"neptunium","de":u"neptunium","tr":u"neptunyum","sv":u"neptunium","ar":u"نبتونيوم","cs":u"neptunium","fi":u"neptunium","ja":u"キシイカウム","es":u"neptunio"},
'PROTON_NUMBER': 93, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Pu': { 'EN': 1.28, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 244.0642, 'NAME_LAT': u'plutonium', 'COLUMN': 106, 'ATOM_SYMBOL': u'Pu', 'OX_NUMBERS': [7, 6, 5, 4, 3], 'NAMES':{"ru":u"плутоний","fr":u"plutonium","en":u"plutonium","nl":u"plutonium","de":u"plutonium","tr":u"plutonyum","sv":u"plutonium","ar":u"بلوتونيوم","cs":u"plutonium","fi":u"plutonium","ja":u"シルエカウム","es":u"plutonio"},
'PROTON_NUMBER': 94, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Am': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 243.0614, 'NAME_LAT': u'americium', 'COLUMN': 107, 'ATOM_SYMBOL': u'Am', 'OX_NUMBERS': [6, 5, 4, 3], 'NAMES':{"ru":u"америций","fr":u"américium","en":u"americium","nl":u"americium","de":u"amerizium","tr":u"amerikyum","sv":u"americium","ar":u"أمريكيوم","cs":u"americium","fi":u"amerikium","ja":u"アメリシウム","es":u"amerício"},
'PROTON_NUMBER': 95, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Cm': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 247.0703, 'NAME_LAT': u'curium', 'COLUMN': 108, 'ATOM_SYMBOL': u'Cm', 'OX_NUMBERS': [4, 3], 'NAMES':{"ru":u"кюрий","fr":u"curium","en":u"curium","nl":u"curium","de":u"kurium","tr":u"curiyum","sv":u"curium","ar":u"كوريوم","cs":u"curium","fi":u"curium","ja":u"キュリウム","es":u"curio"},
'PROTON_NUMBER': 96, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Bk': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 247.0703, 'NAME_LAT': u'berkelium', 'COLUMN': 109, 'ATOM_SYMBOL': u'Bk', 'OX_NUMBERS': [4, 3], 'NAMES':{"ru":u"беркелий","fr":u"berkélium","en":u"berkelium","nl":u"berkelium","de":u"berkelium","tr":u"berkelyum","sv":u"berkelium","ar":u"بركليوم","cs":u"berkelium","fi":u"berkelium","ja":u"バークリウム","es":u"berkelio"},
'PROTON_NUMBER': 97, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Cf': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 251.0796, 'NAME_LAT': u'californium', 'COLUMN': 110, 'ATOM_SYMBOL': u'Cf', 'OX_NUMBERS': [4, 3], 'NAMES':{"ru":u"калифорний","fr":u"californium","en":u"californium","nl":u"californium","de":u"kalifornium","tr":u"kaliforniyum","sv":u"californium","ar":u"كاليفورنيوم","cs":u"californium","fi":u"kalifornium","ja":u"カリセルカウム","es":u"californio"},
'PROTON_NUMBER': 98, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Es': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 252.0829, 'NAME_LAT': u'einsteinium', 'COLUMN': 111, 'ATOM_SYMBOL': u'Es', 'OX_NUMBERS': [3], 'NAMES':{"ru":u"эйнштейний","fr":u"einsteinium","en":u"einsteinium","nl":u"einsteinium","de":u"einsteinium","tr":u"eınsteınyum","sv":u"einsteinium","ar":u"انيشتنيوم","cs":u"einsteinium","fi":u"einsteinium","ja":u"アインスタイカウム","es":u"einstenio"},
'PROTON_NUMBER': 99, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Fm': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 257.0951, 'NAME_LAT': u'fermium', 'COLUMN': 112, 'ATOM_SYMBOL': u'Fm', 'OX_NUMBERS': [3], 'NAMES':{"ru":u"фермий","fr":u"fermium","en":u"fermium","nl":u"fermium","de":u"fermium","tr":u"fermiyum","sv":u"fermium","ar":u"فرميوم","cs":u"fermium","fi":u"fermium","ja":u"サェルミウム","es":u"fermio"},
'PROTON_NUMBER': 100, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Md': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 258.0986, 'NAME_LAT': u'mendelevium', 'COLUMN': 113, 'ATOM_SYMBOL': u'Md', 'OX_NUMBERS': [3], 'NAMES':{"ru":u"менделевий","fr":u"mendélévium","en":u"mendelevium","nl":u"mendelevium","de":u"mendelevium","tr":u"mendelevyum","sv":u"mendelevium","ar":u"مندلفيوم","cs":u"mendelevium","fi":u"mendelevium","ja":u"メンェレコウム","es":u"mendelevio"},
'PROTON_NUMBER': 101, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'No': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 259.1009, 'NAME_LAT': u'nobelium', 'COLUMN': 114, 'ATOM_SYMBOL': u'No', 'OX_NUMBERS': [3, 2], 'NAMES':{"ru":u"нобелий","fr":u"nobélium","en":u"nobelium","nl":u"nobelium","de":u"nobelium","tr":u"nobelyum","sv":u"nobelium","ar":u"نوبليوم","cs":u"nobelium","fi":u"nobelium","ja":u"ギースリウム","es":u"nobelio"},
'PROTON_NUMBER': 102, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Lr': { 'EN': 1.3, 'group':{"cs":u"kovy vzácných zemin","en":u"rare-earth-metals","pt":u"metais-terrosos raros"},
'ATOM_WEIGHT': 262.11, 'NAME_LAT': u'lawrencium', 'COLUMN': 3, 'ATOM_SYMBOL': u'Lr', 'OX_NUMBERS': [3], 'NAMES':{"ru":u"лоуренсий","fr":u"lawrencium","en":u"lawrencium","nl":u"lawrencium","de":u"lawrencium","tr":u"lawrenciyum","sv":u"lawrencium","ar":u"لورنسيوم","cs":u"lawrencium","fi":u"lawrencium","ja":u"ローレンシウム","es":u"lawrencio"},
'PROTON_NUMBER': 103, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Rf': { 'EN': 0.0, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 261.1089, 'NAME_LAT': u'rutherfordium', 'COLUMN': 4, 'ATOM_SYMBOL': u'Rf', 'OX_NUMBERS': [], 'NAMES':{"ru":u"курчатовий","fr":u"rutherfordium","en":u"rutherfordium","nl":u"rutherfordium","de":u"rutherfordium","sv":u"rutherfordium","cs":u"rutherfordium","fi":u"rutherfordium","es":u"ruterfordio"},
'PROTON_NUMBER': 104, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Db': { 'EN': 0.0, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 262.1144, 'NAME_LAT': u'dubnium', 'COLUMN': 5, 'ATOM_SYMBOL': u'Db', 'ORBITALS': 'Rn 5f14 6d3 7s2',
'OX_NUMBERS': [], 'NAMES':{"ru":u"нильсборий","fr":u"dubnium","en":u"dubnium","nl":u"dubnium","de":u"dubnium","sv":u"dubnium","cs":u"dubnium","fi":u"dubnium","es":u"dubnio"},
'PROTON_NUMBER': 105, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Sg': { 'EN': 0.0, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 263.1186, 'NAME_LAT': u'seaborgium', 'COLUMN': 6, 'ATOM_SYMBOL': u'Sg', 'OX_NUMBERS': [], 'NAMES':{"ru":u"сиборгий","fr":u"seaborgium","en":u"seaborgium","nl":u"seaborgium","de":u"seaborgium","sv":u"seaborgium","cs":u"seaborgium","fi":u"seaborgium","es":u"seaborgio"},
'PROTON_NUMBER': 106, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Bh': { 'EN': 0.0, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 262.1231, 'NAME_LAT': u'bohrium', 'COLUMN': 7, 'ATOM_SYMBOL': u'Bh', 'OX_NUMBERS': [], 'NAMES':{"ru":u"борий","fr":u"bohrium","en":u"bohrium","nl":u"bohrium","de":u"bohrium","sv":u"bohrium","cs":u"bohrium","fi":u"bohrium","es":u"bohrio"},
'PROTON_NUMBER': 107, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Hs': { 'EN': 0.0, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 265.1306, 'NAME_LAT': u'hassium', 'COLUMN': 8, 'ATOM_SYMBOL': u'Hs', 'OX_NUMBERS': [], 'NAMES':{"ru":u"хассий","fr":u"hassium","en":u"hassium","nl":u"hassium","de":u"hassium","sv":u"hassium","cs":u"hassium","fi":u"hassium","es":u"hassio"},
'PROTON_NUMBER': 108, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
'Mt': { 'EN': 0.0, 'group':{"cs":u"kovy","en":u"metals","pt":u"metais"},
'ATOM_WEIGHT': 266.1378, 'NAME_LAT': u'meitnerium', 'COLUMN': 9, 'ATOM_SYMBOL': u'Mt', 'OX_NUMBERS': [], 'NAMES':{"ru":u"майтнерий","fr":u"meitnérium","en":u"meitnerium","nl":u"meitnerium","de":u"meitnerium","sv":u"meitnerium","cs":u"meitnerium","fi":u"meitnerium","es":u"meitnerio"},
'PROTON_NUMBER': 109, 'DESC':{"cs":u"","en":u""},
'ROW': 7, },
}

group2color = { 'rare-earth-metals' : 'rgb(181, 182, 176)',
'inert-gases' : 'rgb(253, 71, 3)',
'halogens' : 'rgb(255, 153, 102)',
'alkali-metals' : 'rgb(254, 219, 0)',
'other-metals' : 'rgb(65, 137, 221)',
'metals' : 'rgb(255, 159, 0)',
'alkali-earth-metals' : 'rgb(161, 189, 234)',
'non-metals' : 'rgb(135, 211, 0)',
}
